# Generated by Django 4.2.5 on 2023-09-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80)),
                ('age', models.PositiveIntegerField()),
                ('ismarried', models.BooleanField(default=False)),
                ('salary', models.PositiveIntegerField()),
            ],
        ),
    ]
