# Generated by Django 4.2.5 on 2023-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='name_en',
            field=models.CharField(default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='name_ru',
            field=models.CharField(default='', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='teachermodel',
            name='name_uz',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
